dist: trusty
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - clang-tidy-5.0
      - gcc-7
      - g++-7
language:
  - c
  - c++
env:
  global:
    - GOOGLETEST_VERSION=1.8.0
    - NANOPB_VERSION=58af4d1fb733c5348b68dd3980f2a230d95400b4
  matrix:
    - PROTOBUF_VERSION=2.6.1 MYCC=gcc-7
    - PROTOBUF_VERSION=2.6.1 MYCC=clang-5.0
    - PROTOBUF_VERSION=3.5.0 MYCC=gcc-7
    - PROTOBUF_VERSION=3.5.0 MYCC=clang-5.0
    - LINT=1 PROTOBUF_VERSION=3.1.0 MYCC=clang-5.0
install: ./.travis-install.sh
script: ./.travis-script.sh
